"""empty message

Revision ID: 2610b84c0bf5
Revises: e0e6530b2ce4
Create Date: 2016-11-26 12:12:58.727105

"""

# revision identifiers, used by Alembic.
revision = '2610b84c0bf5'
down_revision = 'e0e6530b2ce4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('tag', sa.String(length=40), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'tag')
    ### end Alembic commands ###
