"""empty message

Revision ID: 48c5a5bb98cf
Revises: cca93c217647
Create Date: 2017-05-07 21:24:44.542992

"""

# revision identifiers, used by Alembic.
revision = '48c5a5bb98cf'
down_revision = 'cca93c217647'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_server', sa.Column('public_server', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_server', 'public_server')
    ### end Alembic commands ###
