"""empty message

Revision ID: 5b607892c512
Revises: 8bc3fc909d1a
Create Date: 2016-07-04 14:10:11.990891

"""

# revision identifiers, used by Alembic.
revision = '5b607892c512'
down_revision = '8bc3fc909d1a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('forfeit', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'forfeit')
    ### end Alembic commands ###
