"""empty message

Revision ID: 8bc3fc909d1a
Revises: c18a8e939c8e
Create Date: 2016-07-03 12:23:37.506842

"""

# revision identifiers, used by Alembic.
revision = '8bc3fc909d1a'
down_revision = 'c18a8e939c8e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'overtime_enabled')
    op.drop_column('match', 'playout_enabled')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('playout_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('match', sa.Column('overtime_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    ### end Alembic commands ###
