"""empty message

Revision ID: b28b5677726e
Revises: 48c5a5bb98cf
Create Date: 2018-07-13 21:04:38.321422

"""

# revision identifiers, used by Alembic.
revision = 'b28b5677726e'
down_revision = '48c5a5bb98cf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'veto_mappool',
               existing_type=mysql.VARCHAR(length=160),
               type_=sa.String(length=500),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'veto_mappool',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=160),
               existing_nullable=True)
    ### end Alembic commands ###
