"""empty message

Revision ID: c18a8e939c8e
Revises: 54c17052c8f4
Create Date: 2016-06-24 17:51:27.163512

"""

# revision identifiers, used by Alembic.
revision = 'c18a8e939c8e'
down_revision = '54c17052c8f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_server', sa.Column('display_name', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_server', 'display_name')
    ### end Alembic commands ###
