"""empty message

Revision ID: cca93c217647
Revises: 2610b84c0bf5
Create Date: 2017-05-01 14:37:44.151074

"""

# revision identifiers, used by Alembic.
revision = 'cca93c217647'
down_revision = '2610b84c0bf5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('public_team', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_team_public_team'), 'team', ['public_team'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_public_team'), table_name='team')
    op.drop_column('team', 'public_team')
    ### end Alembic commands ###
