"""empty message

Revision ID: e0e6530b2ce4
Revises: d84462b5a7a5
Create Date: 2016-10-15 17:27:25.799908

"""

# revision identifiers, used by Alembic.
revision = 'e0e6530b2ce4'
down_revision = 'd84462b5a7a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_stats', sa.Column('firstdeath_Ct', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('firstdeath_t', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('firstkill_ct', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('firstkill_t', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_stats', 'firstkill_t')
    op.drop_column('player_stats', 'firstkill_ct')
    op.drop_column('player_stats', 'firstdeath_t')
    op.drop_column('player_stats', 'firstdeath_Ct')
    ### end Alembic commands ###
